This is a stub of the iOS clipboard logic.
hecrj/window_clipboard pull request #1
Opened 2019-12-22 04:06 UTC by simlay

This is a stub to make the iOS pull request for iced work with the latest master branch.

From what I can tell, mobile clipboards are a pain. It's more or less built into the UITextInput logic (you tap and hold and it pops up a "copy/paste" menu). It very well might be time to look into making the iOS support be a top level platform similar to the web stuff.

2019-12-23 11:13 UTC, hecrj requested changes
I was hoping you would take a look at this. Thanks!

I imagine clipboard access is related to the iOS IME? Is there any way to bring it up with just a window handle?

2019-12-23 11:13 UTC, hecrj commented on src/platform/not_linux.rs
> +        unimplemented!();
Would it be better to return an `Error` here instead of panicking?

I think we could also put this implementation inside the module above.

2020-02-22 17:20 UTC, simlay commented
@hecrj Done! Want me to squash the commits?

2020-03-06 02:37 UTC, hecrj approved these changes

2020-03-06 02:37 UTC, hecrj commented on src/platform/not_linux.rs
> +mod clipboard_ios {
May be a good idea to make this a crate in the long run :wink:

2020-03-06 02:38 UTC, hecrj commented
Looks good. Thank you! :tada:

2020-03-06 02:38 UTC, merged